makefile cleanup and ci jobs update (#213)

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,47 +1,57 @@
-name: Release
+name: release
 on:
-  release:
-    types:
-      - created
+  push:
+    tags:
+      - 'v*'
 env:
-  NAME: victoriametrics-datasource
-  TAG: ${{ github.event.release.tag_name }}
+  PKG_TAG: ${{  github.ref_name }}
 jobs:
   release:
     name: Release on GitHub
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-latest
+    permissions:
+      packages: write
+      contents: write
+      pages: write
     steps:
       - name: Check out code
-        uses: actions/checkout@v2
-      - name: Build Project
+        uses: actions/checkout@v4
+      - name: Setup golang caches
+        uses: actions/cache@v4
+        with:
+          path: |
+            ${{ github.workspace }}/gocache-for-docker
+          key: ${{ runner.os }}-golang-${{ hashFiles('go.sum') }}
+          restore-keys: |
+            ${{ runner.os }}-golang-
+      - name: Setup node caches
+        uses: actions/cache@v4
+        with:
+          path: |
+            ${{ github.workspace }}/.cache
+          key: ${{ runner.os }}-yarn-${{ hashFiles('package.json') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
+      - name: Build plugin
         run: |
-          yarn install
-          npm run build
-      - name: Build ZIP
+          yq -iP '.version="${{ env.PKG_TAG }}"' package.json -o json
+          make vm-plugin-release
+      - name: Prepare release notes
         run: |
-          cp -r ./dist ./${{ env.NAME }} && zip ${{ env.NAME }}-${{ env.TAG }}.zip ${{ env.NAME }} -r && rm -rf ${{ env.NAME }}
-          sha1sum ./${{ env.NAME }}-${{ env.TAG }}.zip >${{ env.NAME }}-${{ env.TAG }}.zip.sha1
-      - name: Upload Release Asset
-        id: upload-release-asset
-        uses: actions/upload-release-asset@v1
+          if grep -q "^## tip$" CHANGELOG.md; then
+            echo "Processing CHANGELOG"
+          else
+            echo "ERROR: Not found 'tip' section in CHANGELOG. Please add relavant entries and recreate git tag"
+            exit 1
+          fi
+          export NOTES="$(sed -n '/# tip/,/## /p' CHANGELOG.md | sed -e '$d' -e '1d')"
+          sed -i 's/## tip/&\n\n## ${{ env.PKG_TAG }}/' CHANGELOG.md
+          cat <<EOT > NOTES.md
+          ## ${{ env.PKG_TAG }}
+          $NOTES
+          EOT
+      - name: Upload release assets
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ github.event.release.upload_url }}
-          asset_path: ./${{ env.NAME }}-${{ env.TAG }}.zip
-          asset_name: ${{ env.NAME }}-${{ env.TAG }}.zip
-          asset_content_type: application/zip
-      - name: Upload Release SHA
-        id: upload-release-sha
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ github.event.release.upload_url }}
-          asset_path: ./${{ env.NAME }}-${{ env.TAG }}.zip.sha1
-          asset_name: ${{ env.NAME }}-${{ env.TAG }}.zip.sha1
-          asset_content_type: application/zip
-      - name: Update version package.json
-        uses: pocket-apps/action-update-version@v1
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh release create ${{ env.PKG_TAG }} ./dist/*
